version: 2.1

commands:
  print_pipeline_id:
    parameters:
      id:
        type: string
    steps:
      - run: echo << parameter.id >>

jobs:
  new_job:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id:
          id: << pipeline.id >>

workflows:
  new_work_flow:
    jobs:
      - new_job
